### ISSUE TITLE
ValueError: set_wakeup_fd only works in main thread

### ISSUE THREAD

**Issue by kazann116** [pyscripter/python4delphi#231]
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "C:\Users\545\AppData\Roaming\Python\Python38\site-packages\telethon\client\telegrambaseclient.py", line 245, in __init__
    self._loop = asyncio.get_event_loop()
  File "C:\Users\545\AppData\Local\Programs\Python\Python38\Lib\asyncio\events.py", line 636, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "C:\Users\545\AppData\Local\Programs\Python\Python38\Lib\asyncio\events.py", line 656, in new_event_loop
    return self._loop_factory()
  File "C:\Users\545\AppData\Local\Programs\Python\Python38\Lib\asyncio\windows_events.py", line 310, in __init__
    super().__init__(proactor)
  File "C:\Users\545\AppData\Local\Programs\Python\Python38\Lib\asyncio\proactor_events.py", line 632, in __init__
    signal.set_wakeup_fd(self._csock.fileno())
ValueError: set_wakeup_fd only works in main thread

I'm trying to call a python function in the delphi stream, it gives such an error, if I call on the button from the form everything works well

**Comment by pyscripter** [comment]
Why do you assume this is a P4D bug?  Your application crashes because a function is called from a thread that is supposed to be called only from the main thread.  Anyway mixing asyncio with the Delphi message loop is very tricky.

**Comment by kazann116** [comment]
how can i fix it there are options?

**Comment by pyscripter** [comment]
Sorry, this is a bug trucker.  Not a "help me fix a problem in my code" forum.
