### ISSUE TITLE
OpenCV - Import Error: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by wesleybobato** [pyscripter/python4delphi#78]
Hello, I'm trying to use python 3.7 and OpenCV 4.01 and I get an error in Delphi Tokyo.

import cv2

ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\PC\Downloads\python\python4delphi-master\python4delphi-master\PythonForDelphi\Demos\Demo01\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import

Running this command in Python's IDLE/Shell works correctly Any suggestions? Can you check this?

Thank you.

**Comment by pyscripter** [comment]
See #69
